version: '2'

services:
  traefik:
    image: traefik:1.4
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
      - "9000:9000"
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dataVolumes/traefik/traefik.toml:/traefik.toml
      - /dataVolumes/traefik/acme:/acme
      - /dataVolumes/traefik/logs:/logs
    networks:
      - traefik_default

 
  tile38:
    image: tile38/tile38
    labels:
      - "traefik.backend=tile38"
      - "traefik.port=9851"
    restart: on-failure
    volumes:
      - /dataVolumes/spatialindex:/data
    networks:
      - traefik_default

#  ipfs:
#    image: ipfs/go-ipfs:latest
#    labels:
#      - "traefik.backend=ipfs"
#      - "traefik.frontend.rule=Host:ipfs.geodex.org"
#      - "traefik.port=4001"
#      - "traefik.port=5001"
#      - "traefik.port=8080"
#    volumes:
#      - /dataVolumes/ipfs/data:/data/ipfs
#      - /dataVolumes/ipfs/staging:/export
#    networks:
#      - traefik_default


  s3system:
    image: minio/minio:latest
    labels:
      - "traefik.backend=s3system"
      - "traefik.frontend.rule=Host:oss.geodex.org"
      - "traefik.port=9000"
    volumes:
      - /dataVolumes/s3:/data
    environment:
      - MINIO_ACCESS_KEY=YUUUWSRXEXACIGAWNPKJ
      - MINIO_SECRET_KEY=AJFZEOXAQEELRCGFIJZS
    networks:
      - traefik_default
    command: ["server", "/data"]


networks:
  traefik_default:
