version: '2'

services:
  traefik:
    image: traefik:1.4
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    networks:
      - traefik_default

  s3system:
    image: minio/minio:latest
    labels:
      - "traefik.backend=s3system"
      - "traefik.port=9000"
    ports:
      - "9000:9000"
    volumes:
      - /home/fils/Data/P418/dataVolumes/s3/data:/data
      - /home/fils/Data/P418/dataVolumes/s3/config:/root/.minio
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    networks:
      - traefik_default
    command: ["server", "/data"]

  headless:
    image: knqz/chrome-headless
    labels:
      - "traefik.backend=headlesschrome"
      - "traefik.port=9222"
    ports:
      - "9222:9222"
    networks:
      - traefik_default

networks:
  traefik_default:
